# Generated by Django 5.1.4 on 2025-01-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in weeks')),
                ('pdf', models.FileField(blank=True, help_text='Upload the course PDF file', null=True, upload_to='course_pdfs/')),
                ('is_active', models.BooleanField(default=True, help_text='Is the course currently active?')),
                ('school', models.ForeignKey(help_text='School offering this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='School.school')),
            ],
        ),
    ]
