# Generated by Django 5.1.4 on 2025-01-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recent_Event',
        ),
        migrations.DeleteModel(
            name='Upcoming_Event',
        ),
    ]
