# Generated by Django 5.1.4 on 2025-01-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_delete_recent_event_delete_upcoming_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_event', to='School.school')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_Event',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_event', to='School.school')),
            ],
        ),
    ]
